source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'LYSandbox_Example' do
	pod 'LYSandbox', :path => '../'

	target 'LYSandbox_Tests' do
		inherit! :search_paths
	end
end
